version: "3.8"
services:
  db:
    container_name: postgres_container2
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DbLMSEduTechIBE
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    container_name: dotnet_app
    image: api-asp
    build:
      context: ./EdutechDAD
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - pgadmin
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    container_name: frontend-services
    image: app-prod-i
    stdin_open: true
    tty: true
    build:
      context: ./edutech
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
